MAX_LOGIN_LENGTH = 20

MIN_LOGIN_LENGTH = 5
MIN_PASSWORD_LENGTH = 5

STAGE_PROJECT_NOT_STARTED = 0
STAGE_PROJECT_STARTED = 1
STAGE_PROJECT_FINISHED = 2

ACTIVITY_CONTRACT_NOT_MADE = 0
ACTIVITY_CONTRACT_MADE = 1
ACTIVITY_CONTRACT_TERMINATED = 2
ACTIVITY_CONTRACT_FINISHED = 3

ROLE_DEVELOPER = 0
ROLE_MANAGER = 1