SET storage_engine=INNODB;
SET AUTOCOMMIT=0;

CREATE TABLE IF NOT EXISTS Companies(
			Id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
			Name TEXT NOT NULL, 
			Details TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS Users(
			Login VARCHAR(20) PRIMARY KEY, 
			Password TEXT NOT NULL,
			Admin BOOL DEFAULT FALSE);
			
CREATE TABLE IF NOT EXISTS Employees(
			Id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
			Name TEXT NOT NULL,
			CompanyId INT UNSIGNED NOT NULL, 
			Login VARCHAR(20) NOT NULL,
			FOREIGN KEY (CompanyId) REFERENCES Companies(Id) ON UPDATE CASCADE ON DELETE CASCADE,
			FOREIGN KEY (Login) REFERENCES Users(Login) ON UPDATE CASCADE ON DELETE CASCADE
			);
			
CREATE TABLE IF NOT EXISTS Projects(
			Id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
			Name TEXT NOT NULL,
			StartDate DATETIME NOT NULL,
			Stage INT NOT NULL);
			
CREATE TABLE IF NOT EXISTS Contracts(
			Id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
			CompanyId INT UNSIGNED NOT NULL,
			ProjectId INT UNSIGNED NOT NULL,
			Activity INT NOT NULL,
			FOREIGN KEY (CompanyId) REFERENCES Companies(Id) ON UPDATE CASCADE ON DELETE CASCADE,
			FOREIGN KEY (ProjectId) REFERENCES Projects(Id) ON UPDATE CASCADE ON DELETE CASCADE);
			
CREATE TABLE IF NOT EXISTS ProjectEmployees(
			EmployeeId INT UNSIGNED NOT NULL,
			ProjectId INT UNSIGNED NOT NULL,
			Role INT NOT NULL DEFAULT 0,
			PRIMARY KEY(EmployeeId, ProjectId),
			FOREIGN KEY (ProjectId) REFERENCES Projects(Id) ON UPDATE CASCADE ON DELETE CASCADE,
			FOREIGN KEY (EmployeeId) REFERENCES Employees(Id) ON UPDATE CASCADE ON DELETE CASCADE);
			
CREATE TABLE IF NOT EXISTS Task(
			Id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
			Name TEXT NOT NULL,
			ProjectId INT UNSIGNED NOT NULL,
			PlannedTime INT NOT NULL,
			CompletionDate DATETIME,
			FOREIGN KEY (ProjectId) REFERENCES Projects(Id) ON UPDATE CASCADE ON DELETE CASCADE);
			
CREATE TABLE IF NOT EXISTS Jobb(
			EmployeeId INT UNSIGNED NOT NULL,
			TaskId INT UNSIGNED NOT NULL,
			StartDate DATETIME,
			CompletionDate DATETIME,
			Description TEXT,
			PRIMARY KEY(EmployeeId, TaskId),
			FOREIGN KEY (EmployeeId) REFERENCES Employees(Id) ON UPDATE CASCADE ON DELETE CASCADE,
			FOREIGN KEY (TaskId) REFERENCES Task(Id) ON UPDATE CASCADE ON DELETE CASCADE
			);
			
CREATE TABLE IF NOT EXISTS TasksDependency(
			MasterId INT UNSIGNED NOT NULL REFERENCES Task(Id) ON DELETE CASCADE 
			ON UPDATE CASCADE,
			SlaveId INT UNSIGNED NOT NULL REFERENCES Task(Id) ON DELETE CASCADE 
			ON UPDATE CASCADE,
			PRIMARY KEY(MasterId, SlaveId),
			FOREIGN KEY (MasterId) REFERENCES Task(Id) ON UPDATE CASCADE ON DELETE CASCADE,
			FOREIGN KEY (SlaveId) REFERENCES Task(Id) ON UPDATE CASCADE ON DELETE CASCADE);